name: GitHub Actions Create staging PR when PR merged to development
on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        - name: pull-request
          uses: repo-sync/pull-request@v2
          with:
            destination_branch: "staging"
            pr_title: "${{ github.ref }}"
            pr_body: "Pulling {{ github.ref }} to staging"
            pr_reviewer: "fabregus"
            pr_assignee: "fabregus"
            github_token: ${{ secrets.GITHUB_TOKEN }}
