name: GitHub Actions Create staging PR when PR merged to development
on:
    pull_request_target:
        branches:
            - main
        types:
            - closed

jobs:
    if_merged_and_website_branch:
        if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'web')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: pull-request
              uses: repo-sync/pull-request@v2
              with:
                  source_branch: "${{ github.head_ref }}"
                  destination_branch: "staging"
                  pr_title: "${{ github.event.pull_request.title }} to staging"
                  pr_body: "${{ github.event.pull_request.body }}"
                  pr_reviewer: "fabregus"
                  pr_assignee: "${{ github.event.pull_request.user.login }}"
                  github_token: ${{ secrets.GITHUB_TOKEN }}
    slackNotification:
        name: Slack Notification
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
                  VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
