name: GitHub Actions Create staging PR when PR merged to development
on:
    push:
        branches: ["main"]

jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: pull-request
              uses: repo-sync/pull-request@v2
              with:
                  source_branch: "${{ github.ref_name }}"
                  destination_branch: "staging"
                  pr_title: "${{ github.ref_name }} to staging"
                  pr_body: "Pulling ${{ github.ref_name }} to staging"
                  pr_reviewer: "fabregus"
                  pr_assignee: "fabregus"
                  github_token: ${{ secrets.GITHUB_TOKEN }}
